### ISSUE TITLE
Model Inference

### ISSUE THREAD

**Issue by AhmedHashish123** [zhenglab/IntrinsicHarmony#1]
Hello, is there a way to infer the model by reading an image and passing the image and its mask to the model and getting the harmonized output? Without the need to store the image's path in a text file and reading it from the text file then loading the image?

**Comment by guozonghui** [comment]
Of course you can load images without text file, for example, you can directly use the file name or traverse the directory file, and append the file name to image_path variable.

**Comment by AhmedHashish123** [comment]
Thank you
